services:

  #####
  # reverse proxy for the whole environment
  #####

  nginx:
    image: nginx:1.29.4-alpine
    network_mode: host
    environment:
      NGINX_PORT: ${NGINX_PORT}
      DEV_API_PORT: ${DEV_API_PORT}
      DEV_UI_PORT: ${DEV_UI_PORT}
      SD_PORT: ${SD_PORT}
    volumes:
      - ./dev/resources/nginx.conf.template:/etc/nginx/templates/default.conf.template:ro
      - ./dev/data/:/data

  #####
  # related services from the data-fair stack
  #####

  simple-directory:
    image: ghcr.io/data-fair/simple-directory:8
    network_mode: host
    depends_on:
      - mongo
    environment:
      PORT: ${SD_PORT}
      DEBUG: session
      ADMINS: '["superadmin@test.com"]'
      PUBLIC_URL: http://localhost:${NGINX_PORT}/simple-directory
      MAILDEV_ACTIVE: "true"
      STORAGE_TYPE: file
      ROLES_DEFAULTS: '["admin", "contrib", "user"]'
      OBSERVER_ACTIVE: "false"
      AUTHRATELIMIT_ATTEMPTS: "1000"
      CIPHER_PASSWORD: dev
      CONTACT: contact@test.com
      MONGO_URL: mongodb://localhost:${MONGO_PORT}/simple-directory
    volumes:
      - ./dev/resources/users.json:/app/data/users.json
      - ./dev/resources/organizations.json:/app/data/organizations.json

  #####
  # db and search engine
  #####

  mongo:
    image: mongo:7
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: