// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ConfirmMenu: typeof import('./src/components/confirm-menu.vue')['default']
    DeviceCard: typeof import('./src/components/device-card.vue')['default']
    ErrorAlert: typeof import('./src/components/error-alert.vue')['default']
    RegisterDevice: typeof import('./src/components/register-device.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubscribeTopic: typeof import('./src/components/subscribe-topic.vue')['default']
    SubscribeWebhook: typeof import('./src/components/subscribe-webhook.vue')['default']
    WebhookHistory: typeof import('./src/components/webhook-history.vue')['default']
    WebhookHistoryItem: typeof import('./src/components/webhook-history-item.vue')['default']
    WebhookSubscriptionForm: typeof import('./src/components/webhook-subscription-form.vue')['default']
  }
}
